apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-fluentd
  namespace: kube-system
  labels:
    k8s-app: simple-fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: simple-fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: simple-fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: simple-fluentd
        image: mp3monster/simple-fluentd-daemonset:v1
        env:
          - name:  FLUENT_FOWARD_HOST
            value: "192.168.1.130"
          - name:  FLUENT_FOWARD_PORT
            value: "28080"
          - name: FLUENT_SOURCE_PATH
            value: /var/lib/containers/logs-from-log-simulator-in-log-simulator*.*
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/containers